# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

class Rails
  class << self
    attr_accessor :application
  end

  def self.root
    self.application.root
  end
end

class RailsApp
  attr_accessor :prefix
  def root
    "/rails-root"
  end
  def config
    self
  end
  def assets
    self
  end
end

module Rails4
  class Application < RailsApp
    attr_accessor :assets_manifest
    def initialize
      @assets_manifest = {
        "assets" => {},
        "files" => {}
      }
      @prefix = "/assets"
    end
  end
end

module Rails3
  class Application < RailsApp
    attr_accessor :digests
    def initialize
      @digests = {}
      @prefix = "/assets"
    end
  end
end

Rails.application = Rails4::Application.new
